from __future__ import annotations

import json
import shutil
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any, Mapping

from ..model import ValidationError
from ..validation import canonical_json, sha256_file, sha256_text


@dataclass(frozen=True)
class ProjectionPlan:
    provider: str
    target: str
    target_exists: bool
    action: str
    rendered_sha256: str
    input_sha256: str
    backup: str | None = None

    def as_dict(self) -> dict[str, Any]:
        return {
            "provider": self.provider,
            "target": self.target,
            "target_exists": self.target_exists,
            "action": self.action,
            "rendered_sha256": self.rendered_sha256,
            "input_sha256": self.input_sha256,
            "backup": self.backup,
        }


class ProviderAdapter:
    provider_id = "base"
    relative_target = Path(".graph-harness/provider.txt")

    def render(
        self,
        *,
        shared_text: str,
        provider_delta: str = "",
        preferences: Mapping[str, Any] | None = None,
    ) -> str:
        preference_text = json.dumps(dict(preferences or {}), indent=2, sort_keys=True)
        parts = [
            "# Generated by Graph Harness SDLC",
            "",
            f"Provider projection: {self.provider_id}",
            "Do not treat this generated file as the source of truth.",
            "",
            "## Shared Instructions",
            shared_text.strip(),
        ]
        if provider_delta.strip():
            parts.extend(["", "## Provider Delta", provider_delta.strip()])
        if preferences:
            parts.extend(["", "## Developer Preferences", "```json", preference_text, "```"])
        return "\n".join(parts).rstrip() + "\n"

    def plan(
        self,
        *,
        target_root: str | Path,
        shared_text: str,
        provider_delta: str = "",
        preferences: Mapping[str, Any] | None = None,
    ) -> ProjectionPlan:
        root = Path(target_root).expanduser().resolve(strict=False)
        target = root / self.relative_target
        rendered = self.render(
            shared_text=shared_text,
            provider_delta=provider_delta,
            preferences=preferences,
        )
        input_hash = sha256_text(
            canonical_json(
                {
                    "provider": self.provider_id,
                    "shared_text": shared_text,
                    "provider_delta": provider_delta,
                    "preferences": dict(preferences or {}),
                }
            )
        )
        backup = None
        action = "create"
        if target.exists():
            action = "replace-with-backup"
            timestamp = datetime.now(UTC).strftime("%Y%m%dT%H%M%S%fZ")
            backup = str(target.with_name(f"{target.name}.bak.{timestamp}"))
        return ProjectionPlan(
            provider=self.provider_id,
            target=str(target),
            target_exists=target.exists(),
            action=action,
            rendered_sha256=sha256_text(rendered),
            input_sha256=input_hash,
            backup=backup,
        )

    def apply(
        self,
        *,
        target_root: str | Path,
        shared_text: str,
        provider_delta: str = "",
        preferences: Mapping[str, Any] | None = None,
        manifest_root: str | Path | None = None,
        sources: Mapping[str, str] | None = None,
    ) -> ProjectionPlan:
        resolved_target_root = Path(target_root).expanduser().resolve(strict=False)
        if not resolved_target_root.is_dir():
            raise ValidationError(f"provider target root must already exist: {resolved_target_root}")
        plan = self.plan(
            target_root=resolved_target_root,
            shared_text=shared_text,
            provider_delta=provider_delta,
            preferences=preferences,
        )
        if manifest_root is not None:
            manifest_path = Path(manifest_root) / ".graph-harness" / "provider-manifest.json"
            if manifest_path.exists():
                self._read_manifest(manifest_path)
        target = Path(plan.target)
        target.parent.mkdir(parents=True, exist_ok=True)
        if target.exists() and plan.backup:
            shutil.copy2(target, plan.backup)
        rendered = self.render(
            shared_text=shared_text,
            provider_delta=provider_delta,
            preferences=preferences,
        )
        target.write_text(rendered, encoding="utf-8")
        if manifest_root is not None:
            self._update_manifest(
                root=Path(manifest_root),
                plan=plan,
                target_root=resolved_target_root,
                sources=sources or {},
            )
        return plan

    def _update_manifest(
        self,
        *,
        root: Path,
        plan: ProjectionPlan,
        target_root: Path,
        sources: Mapping[str, str],
    ) -> None:
        control_dir = root / ".graph-harness"
        control_dir.mkdir(parents=True, exist_ok=True)
        manifest_path = control_dir / "provider-manifest.json"
        if manifest_path.exists():
            raw = self._read_manifest(manifest_path)
        else:
            raw = {"schema_version": "graph-harness.provider-manifest.v1", "projections": {}}
        projections = raw.setdefault("projections", {})
        if not isinstance(projections, dict):
            raise ValidationError("provider manifest projections must be an object")
        source_hashes: dict[str, str] = {}
        for label, path_text in sources.items():
            path = Path(path_text)
            if path.is_file():
                source_hashes[label] = sha256_file(path)
        target_path = Path(plan.target)
        try:
            target_relative = str(target_path.relative_to(target_root.resolve(strict=False)))
        except ValueError:
            target_relative = str(target_path)
        projections[self.provider_id] = {
            "target_root": str(target_root.resolve(strict=False)),
            "target": target_relative,
            "rendered_sha256": plan.rendered_sha256,
            "input_sha256": plan.input_sha256,
            "sources": {str(label): {"path": str(path), "sha256": source_hashes.get(label)} for label, path in sources.items()},
        }
        manifest_path.write_text(json.dumps(raw, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    @staticmethod
    def _read_manifest(manifest_path: Path) -> dict[str, Any]:
        try:
            raw = json.loads(manifest_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as error:
            raise ValidationError(f"provider manifest is invalid: {error}") from error
        if not isinstance(raw, dict) or raw.get("schema_version") != "graph-harness.provider-manifest.v1":
            raise ValidationError("provider manifest schema_version is unsupported")
        if not isinstance(raw.get("projections", {}), dict):
            raise ValidationError("provider manifest projections must be an object")
        return raw
